### PR TITLE
Add support for dark mode

### PR DESCRIPTION
**Pull request by lnsp**
This pull request adds support for dark mode using `prefers-color-scheme` and improves the format of link lists and headers. [Since a lot of newer browser versions](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) support the `prefers-color-scheme` property, this seems to be the best way to go.

Of course, design and color schemes depends a lot on personal taste so please give feedback!

### Preview

tumsexy-redesign-overview

### CODE REVIEW

**Comment by mammuth** [comment]
Very cool, I like it!

**Comment by jpbernius** [comment]
Thanks for this PR! Very nice.
Can you look at the price display on the "Hunger" page also? I think this can be better.
image

**Comment by lnsp** [comment]
What about replacing the popovers with a table like structure? This should allow for faster visual scanning on mobile.

Screenshot 2019-11-15 at 16 59 03

**Comment by lnsp** [comment]
I believe the PR is ready-for-merge now.

**Comment by mammuth** [comment]
Then let's go for it! Thanks!

**Pull request merged**
