### PR TITLE
Implemented search box

### LINKED ISSUE #81: Add search/filter for redirects
As discussed in #78 a search/filter box might be cool to filter the list of available links.

The filtering should be implemented in-place on the client side without the need of a page refresh.

### PR DESCRIPTION
**Pull request by hbirler**
Resolves #81 
Imported staticsearch.js
Updated the html and css to add a search input box
Updated the css to use flexbox rendering on columns due to issues with hidden elements

### CODE REVIEW

**Comment by mammuth** [comment]
What exact problem did you have with the current grid system? 
I don't think it's a clean approach to still use the classes like `row` from the skeet of CSS framework but overwrite the behaviour with flexbox.

**Comment by hbirler** [comment]
In the current grid system, every .row contains two .column elements. When the search hides, let's say, "2. Semester", but "1. Semester" and "3. Semester" are shown, instead of creating a new row of two, "3. Semester" stays at the line below. That's why I removed the .row elements and instead used flex-box style grids in the wrapper element.
I definitely agree that overriding the styles isn't that clean, I opened the pull request to show how a possible solution might look like and discuss the issues. How should I do it? Should I create new classes and use them instead of .row and .column?

**Comment by mammuth** [comment]
Understand. Well, maybe we should just get rid of skeletons grid system completely and just use flexbox or CSS grid instead.

**Comment by hbirler** [comment]
I looked at the skeleton.css code and it seems like we only need to modify a minimal part of it (Lines 31 - 46). So rather than trying to replace the whole css file, would it be okay just to modify those lines?

**Comment by mammuth** [comment]
Sweet! 🎉

**Pull request merged**
