### PR TITLE
addition of opensearchdescription document

### PR DESCRIPTION
**Pull request by zepatrik**
haven't tested it, but a problem should just show up in the dev console

### CODE REVIEW

**Comment by mammuth** [comment]
@kordianbruck fine with testing it out?

8054 image_thumb_35c6e986

**Comment by kordianbruck** [comment]
Sure, fine by me. 
(There's a space missing in the index but who cares)

**Comment by mammuth** [comment]
Seems to work as intended. The line was added automatically, I just changed the "trigger-phrase" (or whatever it's called).

bildschirmfoto 2017-01-13 um 22 05 55

**Comment by zepatrik** [comment]
Think you can't set that in the file, every user has to edit as prefered

**Pull request merged**
