### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by jpbernius**

### CODE REVIEW

**Comment by kordianbruck** [comment]
Looks good - ready to merge @jpbernius ? 

I tried to find ways around using a webserver inside docker, but I guess its not that easy. Effectively this means, that every container that is serving a website, is running its own webserver which each of those configs might be prone for errors - not a fan.

Apart from that:

- Composer should not install dev dependencies inside the container - use `--no-dev`
- phpunit is not run, as you removed the matrix from travis config
- ideally we first try to unit test our code and then build the image, so errors are detected more quickly

**Comment by jpbernius** [comment]
My laptop is out of batter, feel free to do the fixes yourself.

**Comment by jpbernius** [comment]
@kordianbruck where are we standing?
- Should we stay like this? (based on official php-apache image)
- Should we move to an nginx based base-image? ([e.g. this](http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html))
- Should we move to a two container setup ([like this](http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/)) separating webserver and php.

**Comment by kordianbruck** [comment]
* Yes, its fine
* No, not worth the trouble at the moment
* No, its overkill

I would love to push this to dockerhub - @mammuth can you set this up? Or do we want to move this to deploy this to a private registry? Shouldn't be too hard to do either way.

**Comment by jpbernius** [comment]
We could have [Travis push to docker hub](https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry) or use [automated builds on Docker Hub](https://docs.docker.com/docker-hub/builds/).

**Comment by mammuth** [comment]
I added credentials to dockerhub in the env variables in Travis, so you can do `docker login` in order to push the image.

The registered repository on dockerub is `mammuth/tum.sexy` (send me your dockerhub username if you want me to add you as collaborators).

**Comment by mammuth** [comment]
Ah, actually, I think I setup dockerhub that dockerhub builds the image whenever we push to the github repo, so we don't need travis for that.

Obvious disadvantage: We don't wait for the Travis tests to pass, so maybe we should stick with Travis doing to push to dockerhub.

**Comment by mammuth** [comment]
Cool!

> Should trigger docker hub deployment for tags .

Nah, pull request builds skip the deployment, so we need to merge or in order to test it :wink:

**Comment by mammuth** [comment]
@jpbernius ready for testing it out by merging? (at least the publishing to dockerhub - not sure how far @kordianbruck is with his Traefik setup)

**Comment by jpbernius** [comment]
Yes

**Comment by mammuth** [comment]
> Skipping a deployment with the script provider because this is not a tagged commit

Is this the intended behaviour that we publish the image only when we tag the commit? I'd actually prefer just to always push the image when we merged into master.

**Comment by jpbernius** [comment]
We can change that. But yes as stated above, intended to deploy on tag.

**Comment by mammuth** [comment]
Ah, I see. 
Well, although deploying on tags is fancy - we didn't have versioned releases until now and I don't see why we'd need them, so we should just always deploy the master branch.

**Comment by jpbernius** [comment]
@mammuth see #112

**Pull request merged**
