### PR TITLE
Handle URL rewriting internally

### PR DESCRIPTION
**Pull request by DerGenaue**
Not sure if this works

Could you try this out?
This should make Apache handle all the URL rewriting without sending 302 Found to the browser.

This might even make tum.sexy faster (as there is only one request to do)

### CODE REVIEW

**Comment by kordianbruck** [comment]
How about a leading slash? /redirect/...

**Comment by DerGenaue** [comment]
try and error ;)

**Comment by DerGenaue** [comment]
Ok, try the leading slash then ;)

**Comment by DerGenaue** [comment]
now this is awkward...

**Comment by kordianbruck** [comment]
Please test these in the future ;)

**Comment by DerGenaue** [comment]
Can I just use the standard-excuse?
On my system they are working :P

**Comment by DerGenaue** [comment]
But they are still external... ?!

Could we try the [PT]-flag to force internal routing?

**Comment by kordianbruck** [comment]
It is not working on your system - don't BS me ;)

No, apache should definitely route this internally.

**Comment by DerGenaue** [comment]
Gotta learn reading...

Cached

Works now :+1:

**Comment by kordianbruck** [comment]
:lollipop:  the classic

**Pull request merged**
