### PR TITLE
Cleanup routes.php

### PR DESCRIPTION
**Pull request by hbirler**
Sort routes
Correct spacing
Delete duplicate markov entry

### CODE REVIEW

**Comment by cs8898** [comment]
> Sort Routes
Or i would call ist "Alphabetical Sort" but i don't think thats a good change, bevor there was some logic of the Routes, like the first ones are generic, the next are first semesert ...

> Correct spacing
Jap According to the Style guides can be good

> Delete Duplicate
+1

**Comment by mammuth** [comment]
> Or i would call ist "Alphabetical Sort" but i don't think thats a good change, bevor there was some logic of the Routes, like the first ones are generic, the next are first semesert ...

That order hasn't been actively maintained for quite a while I think. 

Tbh I'm just not a fan of that big diff. And since it won't stay alphabetically for long, it's also not really helpful (*looking* alphabetically but not *being* alphabetically is actually worse than the current "order").

**Comment by jpbernius** [comment]
We could add a test for that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mammuth** [comment]
Jep. Then it would make sense :+1:

**Comment by mammuth** [comment]
Closing this due to the discussion above.

Sorting would be appreciated if you also add a test for that. Also, a hint to the markdown file that explains how to add routes should be added I think.

**Pull request closed without merging**
