### PR TITLE
Move Hunger Price to Tooltip

### PR DESCRIPTION
**Pull request by jpbernius**
Make list more compact by moving price to tooltip:

mac
iphonexspacegrey_portrait

### CODE REVIEW

**Comment by kordianbruck** [comment]
Good idea. @mammuth what do you think?

**Comment by mammuth** [comment]
Not sure about it. Looks fancy but people need to understand they can tap the meal for more information. But we surely can try that if you guys want to.

**Comment by jpbernius** [comment]
Should we invoke the first tooltip automatically on page load, so people get an idea?

**Comment by mammuth** [comment]
Nice idea. 👍 
And let's hide all other tooltips when a new one is shown.

**Comment by mammuth** [comment]
Cool, good to go?

**Pull request merged**
