### PR TITLE
Update routes.php

### PR DESCRIPTION
**Pull request by joschahenningsen**
New URLs for WS 2019 (GBS and FPV)

### CODE REVIEW

**Comment by mammuth** [comment]
Thanks!

Apparently one of the urls was used with our test cases. Could you try to figure that out?

**Comment by mammuth** [comment]
I merged #251 which did changes to FPV. Could you reduce the diff here to gbs?

**Comment by joschahenningsen** [comment]
> I suggest linking directly to moodle for gbs since the faculty website doesn't provide anything useful other than a link to moodle.

You are right, sorry for the trouble!

**Comment by mammuth** [comment]
I think the tests used the gbs route. So you would need to adapt them as well 😉

**Comment by joschahenningsen** [comment]
There is a test case that feels redundant as gbs.tum.sexy routes to moodle now. Should it be removed?

**Comment by mammuth** [comment]
Better replaced with a non-moodle redirect

**Pull request merged**
