### PR TITLE
Github badge on page

### PR DESCRIPTION
**Pull request by mammuth**
Yes, No, Maybe? @kordianbruck @krenzland 

screen shot 2016-10-06 at 15 02 56
Reference: https://github.com/blog/273-github-ribbons

### CODE REVIEW

**Comment by kordianbruck** [comment]
Do we really want people to fork? More like contribute

**Comment by mammuth** [comment]
Well it's an image, provided by github. But you're right, we should make an
own badge that says "Contribute on GitHub".

**Comment by kordianbruck** [comment]
Maybe these? https://buttons.github.io/

**Comment by kordianbruck** [comment]
Or this in css: https://simonwhitaker.github.io/github-fork-ribbon-css/

**Comment by mammuth** [comment]
Closed via https://github.com/mammuth/TUM.sexy/commit/9f7a37f79e90db51842357ef4a008e6590f87405

**Pull request closed without merging**
