### PR TITLE
added TUMMensabot for Telegram

### PR DESCRIPTION
**Pull request by Alwinius**

### CODE REVIEW

**Comment by mammuth** [comment]
Thanks @Alwinius!

I'd rather go for _mensabot_ instead of the generic _mensa_. cc @kordianbruck @krenzland

**Comment by Alwinius** [comment]
Sure, no problem

**Comment by mammuth** [comment]
You need to update the section as well 😉

**Comment by mammuth** [comment]
Thanks, is already deployed.

**Pull request merged**
