### PR TITLE
New Route for Git-starters

### PR DESCRIPTION
**Pull request by highDraze**
https://learngitbranching.js.org is a nice plattform to learn git. Could be handy for starters.

### CODE REVIEW

**Comment by mammuth** [comment]
Hm, TBH I thought we already had git.tum.sexy -> gitlab.lrz.de. But that's not the case. 

Now I'm asking myself which option makes more sense: tutorial or gitlab?

**Comment by highDraze** [comment]
As longer versions I thought of lrz.tum.sexy, git-tut or gitgud.

**Comment by mammuth** [comment]
Maybe git/lrz/gitlab -> gitlab and git-tut -> tutorial makes sense? What do you think?

**Comment by highDraze** [comment]
Work fine.

**Comment by mammuth** [comment]
Do you add the redirects and its synonyms?

**Pull request merged**
