### PR TITLE
Added Two Links

### PR DESCRIPTION
**Pull request by mathiasquintero**
Added a link to a website for my tutorial. :)
And added a link to Carlos Camino's website.

Haven't run it though. I'm guessing it works.

### CODE REVIEW

**Comment by mammuth** [comment]
Thanks for your contirbution @mathiasquintero 

IMHO we shouldn't link a lesson-generic link like propra to the website of a specific group. 
This is rather confusing, since all other redirects are links to the lessons general website, which apply to all students.

Possible compromise: 
- propra30.tum.sexy?
- don't display it on the frontpage since it's not interesting for most of our visitors - you can share the link in your lesson

(btw, isn't it called prop*r*a and not propa?)

**Comment by kordianbruck** [comment]
Then we shouldn't have in there either if we generally say that there shouldn't be any other thing than lectures. Maybe adjust it to propra30 and also add the normal propra website, but in general I wouldn't disallow anything. No/Yes?

**Comment by mammuth** [comment]
I didn't say there shouldn't be other stuff than lectures (of course there should), I just prefer avoiding misleading redirects like propra linking to a specific group, when everyone expects the lesson page as target.

carlos.tum.sexy is not misleading I guess.

Furthermore I suggest hiding links that only affect a small number of people from the frontpage in order to not mess it in the future.

I think this makes sense, doesn't it?

Then a general ruleset might be:
- add everything which is not misleading
- show everything that affects most of the people

**Comment by kordianbruck** [comment]
Sounds good, want to add it to the readme or should I do that?

**Comment by mammuth** [comment]
I'm going to add it to the readme

**Pull request merged**
