### PR TITLE
Update routes.php

### PR DESCRIPTION
**Pull request by hbirler**
Shortened url for convenience

### CODE REVIEW

**Comment by mammuth** [comment]
Thanks. In #62 we found it'd makes sense to enter the long term, since it's more memorable. 

Moreover, most users probably don't always delete their browsing history and as a result get the URL as suggestion, so they don't need to enter the complete subdomain.

**Comment by kordianbruck** [comment]
I would add both. Can we setup a way to have multiple synonyms for one URL?

**Comment by mammuth** [comment]
True, actually no reason to not have synonyms.

**Comment by kordianbruck** [comment]
Done @hbirler - its now added via a simpler synonym possibility.

**Pull request closed without merging**
