### PR TITLE
update gbs url, fix indentation

### PR DESCRIPTION
**Pull request by lukaskollmer**

### CODE REVIEW

**Comment by mammuth** [comment]
Thanks!

Why did you remove the Moodle course id? Does the course don't have a Moodle course this semester?

Also please remove all those whitespace changes.

**Comment by lukaskollmer** [comment]
it does appear to have a moodle course but the url is currently invalid so i wasn't able to conform that it'd be the correct course id.

just out of curiosity, why do you prefer having only some parts of the code indented w/ additional whitespace over using the same indentation style for the entire file?

**Comment by mammuth** [comment]
> just out of curiosity, why do you prefer having only some parts of the code indented w/ additional whitespace over using the same indentation style for the entire file?

I prefer having as small diffs as possible - whitespace changes make it harder to review the "real" changes. 
TBH, in this case I didn't even realise 100% that you indeed fixed the indentation, but somehow was afraid of random whitespace changes (happens often enough 🙈), my bad.

Feel free to make the indentation consistent!

**Comment by lukaskollmer** [comment]
done

**Pull request merged**
