### PR TITLE
added Moodle Courses of Gad and Eist

### PR DESCRIPTION
**Pull request by MW360**

### CODE REVIEW

**Comment by mammuth** [comment]
Thanks. We recently changed the structure of the redirects to support moodle next to the website of a course. You can simply add `moodle_id` (not 100% sure about the spelling) to the course. 

I'm also not sure whether those subsubredirects are functioning after the recent deployment changes (cc @kordianbruck).

**Comment by MW360** [comment]
I'm not shure but i think the certificate of tum.sexy doesn't fit for the feature without extra redirects. I tried m.db.tum.sexy as an example. Is this the right domain?

**Comment by kordianbruck** [comment]
@mammuth there is no way, I can get a wildcard for a wildcard cert. So in theory I would need to setup a DNS "wilcard zone" (e.g.: db.tum.sexy) for the subdomain. Then for each of those subdomains I would need to get another cert (could be wildcard or not). That would mean, we would need to automatically manage our DNS zones from our PHP configuration which is not practical. 

I can check, if we can utilize HSTS without including subdomains, but I'm not sure, on where this header is coming from right now. Meaning 2nd level subdomains would not be forced to use https.

**Comment by mammuth** [comment]
Yep.

I mean we can also just change the way we handle moodle links (like supporting m-gad.tum.sexy or mgad.tum.sexy).

Doing these things in the redirection code is probably easier / easier to maintain as doing it on the infrastructure.

**Comment by kordianbruck** [comment]
Yea, plus we have SSL then :+1:

**Comment by mammuth** [comment]
Okay, then I'll merge this and create a corresponding issue.

**Pull request merged**
